# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cat', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('text_cat', models.TextField(verbose_name='Описание категории')),
            ],
            options={
                'ordering': ['title_cat'],
                'verbose_name_plural': 'Категории',
                'db_table': 'Category_of_Request',
                'get_latest_by': 'order_date',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surename', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('secondname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'ordering': ['surename', 'name', 'secondname'],
                'verbose_name_plural': 'Данные о клиентах',
                'db_tablespace': 'DEFAULT_TABLESPACE',
            },
        ),
        migrations.CreateModel(
            name='Request_of_laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_request', models.PositiveIntegerField(unique=True, verbose_name='Номер заявки')),
                ('create_request', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата создания заявки')),
                ('modify_request', models.DateTimeField(verbose_name='Время и дата изменение заявки')),
                ('delete_request', models.DateTimeField(verbose_name='Время и дата удаления заявки')),
                ('laboratory_title', models.CharField(max_length=100, verbose_name='Название лаборатории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Принадлежность заявки к категории')),
                ('clients', models.ManyToManyField(to='blog.Client')),
            ],
            options={
                'verbose_name_plural': 'Заявки лабораторий',
            },
        ),
        migrations.CreateModel(
            name='Request_of_medcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_request', models.PositiveIntegerField(unique=True, verbose_name='Номер заявки')),
                ('create_request', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата создания заявки')),
                ('modify_request', models.DateTimeField(verbose_name='Время и дата изменение заявки')),
                ('delete_request', models.DateTimeField(verbose_name='Время и дата удаления заявки')),
                ('medcenter_title', models.CharField(max_length=100, verbose_name='Название медицинского центра')),
            ],
            options={
                'verbose_name_plural': 'Заявки медцентров',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('request_of_medcenter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Request_of_medcenter')),
                ('address', models.TextField(verbose_name='Адрес получателя')),
                ('delivery_variant', models.CharField(choices=[('S', 'Самовывоз'), ('K', 'Курьер'), ('N', 'Неопределен')], max_length=1, verbose_name='Вариант доставки')),
                ('delivery_date', models.DateTimeField(verbose_name='Дата и время доставки')),
            ],
            options={
                'verbose_name_plural': 'Доставки',
            },
            bases=('blog.request_of_medcenter',),
        ),
        migrations.AddField(
            model_name='request_of_medcenter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Принадлежность заявки к категории'),
        ),
        migrations.AddField(
            model_name='request_of_medcenter',
            name='clients',
            field=models.ManyToManyField(to='blog.Client'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set([('surename', 'name')]),
        ),
        migrations.CreateModel(
            name='XMLClient',
            fields=[
            ],
            options={
                'proxy': True,
                'ordering': ['surename'],
            },
            bases=('blog.client',),
        ),
    ]
