# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_of_laboratory',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='request_of_medcenter',
            name='clients',
        ),
        migrations.AddField(
            model_name='request_of_laboratory',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.Client', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_of_medcenter',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.Client', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
