# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160717_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFieldMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field2', models.BigIntegerField()),
                ('field3', models.BinaryField()),
                ('field4', models.BooleanField()),
                ('field5', models.CharField(max_length=100)),
                ('field6', models.CommaSeparatedIntegerField(max_length=6)),
                ('field7', models.DateField()),
                ('field8', models.DateTimeField()),
                ('field9', models.DecimalField(decimal_places=6, max_digits=6)),
                ('field10', models.DurationField()),
                ('field11', models.EmailField(max_length=254)),
                ('field12', models.FileField(upload_to='')),
                ('field13', models.FilePathField()),
                ('field14', models.FloatField()),
                ('field15', models.ImageField(upload_to='')),
                ('field16', models.IntegerField()),
                ('field17', models.GenericIPAddressField()),
                ('field18', models.NullBooleanField()),
                ('field19', models.PositiveIntegerField()),
                ('field20', models.PositiveSmallIntegerField()),
                ('field21', models.SlugField()),
                ('field22', models.SmallIntegerField()),
                ('field23', models.TextField()),
                ('field24', models.TimeField()),
                ('field25', models.URLField()),
                ('field26', models.UUIDField()),
                ('field27', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Client')),
                ('field28', models.ManyToManyField(to='blog.Category')),
                ('field29', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
    ]
