# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160721_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='blogex',
            new_name='blogexample',
        ),
    ]
