# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160721_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blogexample',
        ),
        migrations.DeleteModel(
            name='AuthorExample',
        ),
        migrations.DeleteModel(
            name='BlogExample',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
