# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_author1_blog1_entry1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': 'order_date', 'managed': True, 'ordering': ['title_cat'], 'select_on_save': False, 'verbose_name_plural': 'Категории'},
        ),
    ]
